### ISSUE TITLE
Willing To Test!!

### ISSUE THREAD

**Issue by mllockwood** [HRFrazier/hass_microair_climate#1]
I have been searching for a Home Assistant integration of the MicroAir EasyTouch thermostat for about a year now.   I am excited to have found this.  I added the repo to HACS, and installed the Integration.  I have tried to initialize the Integration by entering a Name for the thermostat, as well as the IP addressed assigned to it.  But, I get an error and it does not connect.  The logs show:

Logger: custom_components.microair_climate.config_flow
Source: custom_components/microair_climate/config_flow.py:61
integration: MicroAir_EasyTouch
First occurred: 6:34:10 PM (2 occurrences)
Last logged: 6:34:52 PM

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1073, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
    raise first_exception
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 166, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.10.0.36', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/microair_climate/config_flow.py", line 61, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/microair_climate/config_flow.py", line 42, in validate_input
    if not await hub.test_connection(data[CONF_IP_ADDRESS]):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/microair_climate/coordinator.py", line 67, in test_connection
    resp = await self._session.post(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1088, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.10.0.36:80 ssl:default [Connect call failed ('10.10.0.36', 80)]

![image](https://github.com/user-attachments/assets/7c6ca9f6-51c5-49b1-9193-039004d4d95f)

Any assistance with this is greatly appreciated!  I am more than willing to assist with testing.  Thank you for all the work you've done thus far on this.

**Comment by HRFrazier** [comment]
Hi Michael,

Glad you found it! I did the same... and I figured I'd have to write it for myself. Started with packet capture then some fiddling around in postman, all to figure out they're mostly relaying their data as ascii hex values in HTTP posts.

Quick test- Are you able to use postman to post to 10.10.0.36/ShortStatus? If you can also send me the result from a POST to 10.10.0.36/controls.xml

You should see something like the following, with maybe less lines. (I have 3 thermostats, and realized that they talk to eachother, negotiate their IDs, and relay eachother's status no matter which one you're communicating with. pretty neat actually)

![Screenshot 2024-08-30 093405](https://github.com/user-attachments/assets/c6c53dc1-1b6b-4476-a505-db9c0e10b73f)

**Comment by mllockwood** [comment]
I just downloaded and installed Postman.  I tried sending a POST to 10.10.0.36/ShortStatus and get this:

![image](https://github.com/user-attachments/assets/f796b7c3-5386-4bb5-b33e-1a22ff7d1953)

When I POST to 10.10.0.36/controls.xml, I receive the same error. 

I know that 10.10.0.36 is my thermostat IP address, and it's online, active, and I can ping it.  I just confirmed again comparing the Static IP lease in my router to the thermostat's MAC address.  I'm running Firmware 1.0.6.3 on the thermostat (if that's of importance).

**Comment by HRFrazier** [comment]
Hmm. Ok, does it return anything for controls.xml?
I think that's how the app discovers capabilities.

Also, to clarify, I am using the ASY-389-X50-WIFI. https://www.microair.net/collections/marine-control-displays/products/easytouch-oem-control-display?variant=21562444185684


Maybe you have a different variant, might need to do some discovery with wireshark, hopefully they are similar if you have a different model.

**Comment by mllockwood** [comment]
I am running the ASY-356-X01, which is the 12VDC EasyTouch RV 356 

https://www.microair.net/collections/easytouch-rv-thermostat-coleman-replacements/products/coleman-rv-comfort-2-button-12vdc-only-replacement?variant=43073892876502

I plan to dive in to this a bit more this week to hopefully get some data that might assist with troubleshooting.
